// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-U2F-vdiKdtgSO06V8fhmXABdcqPB4Cw',
    appId: '1:722763183331:web:ddcc4cb76d211a6f1f41d6',
    messagingSenderId: '722763183331',
    projectId: 'flutter-test-85be2',
    authDomain: 'flutter-test-85be2.firebaseapp.com',
    storageBucket: 'flutter-test-85be2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJWsDn1WCRJxap2V7IaCU5dhJP5LwT7gE',
    appId: '1:722763183331:android:a410ec8400be7db11f41d6',
    messagingSenderId: '722763183331',
    projectId: 'flutter-test-85be2',
    storageBucket: 'flutter-test-85be2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnj0Mqvu02s2kPfnYxWqi7Ik2fbwHmhLM',
    appId: '1:722763183331:ios:8a822e79c6f0c68a1f41d6',
    messagingSenderId: '722763183331',
    projectId: 'flutter-test-85be2',
    storageBucket: 'flutter-test-85be2.firebasestorage.app',
    iosBundleId: 'yes',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnj0Mqvu02s2kPfnYxWqi7Ik2fbwHmhLM',
    appId: '1:722763183331:ios:8a822e79c6f0c68a1f41d6',
    messagingSenderId: '722763183331',
    projectId: 'flutter-test-85be2',
    storageBucket: 'flutter-test-85be2.firebasestorage.app',
    iosBundleId: 'yes',
  );

}